import React from "react";
import {render} from 'ink-testing-library';
import App from '../src/app.js';
const cwd = process.argv[2];
const tick = () => new Promise(r => setTimeout(r, 80));
const {stdin, lastFrame} = render(<App args={[]} cwd={cwd} />);
let fail = 0;
const ok = (n: string, c: boolean) => { console.log(c ? 'PASS' : 'FAIL', n); if (!c) fail++; };
await tick();
const f = () => lastFrame() ?? '';
ok('loaded', f().includes('[1/'));
stdin.write('d'); await tick(); ok('plain d no-op', f().includes('[1/'));
stdin.write('\x04'); await tick(); ok('ctrl-d no quit', f().includes('[1/'));
stdin.write('f'); await tick(); ok('modal open', f().includes('Files ('));
stdin.write('j'); await tick(); ok('sel moved', f().includes('Files (2/'));
stdin.write('\x04'); await tick(); ok('ctrl-d in modal', /Files \(\d+\//.test(f()));
stdin.write('n'); await tick(); ok('main keys ignored in modal', f().includes('Files ('));
stdin.write('q'); await tick(); ok('q closes modal', f().includes('[1/'));
stdin.write('f'); await tick(); stdin.write('j'); await tick(); stdin.write('\r'); await tick(); ok('enter jumps', f().includes('[2/'));
stdin.write('f'); await tick(); stdin.write('\x1b'); await tick(); ok('esc closes', f().includes('[2/') && !f().includes('Files ('));
console.log(f());
process.exit(fail ? 1 : 0);
