import React from 'react';
import {render} from 'ink-testing-library';
import App from '../src/app.js';
import {mkdirSync, existsSync, readFileSync} from 'node:fs';
import {join} from 'node:path';
import type {ThemeName} from '../src/theme.js';
const cwd = process.argv[2];
const tick = () => new Promise((r) => setTimeout(r, 80));
const {stdin, lastFrame} = render(<App args={[]} cwd={cwd} />);
let fail = 0;
const ok = (n: string, c: boolean) => {
	console.log(c ? 'PASS' : 'FAIL', n);
	if (!c) fail++;
};
await tick();
const f = () => lastFrame() ?? '';
ok('loaded', f().includes('[1/'));
stdin.write('d');
await tick();
ok('d half page ok', f().includes('[1/'));
stdin.write('\x04');
await tick();
ok('ctrl-d ignored, no quit', f().includes('[1/'));
stdin.write('f');
await tick();
ok('modal open', f().includes('Files ('));
stdin.write('j');
await tick();
ok('sel moved', f().includes('Files (2/'));
stdin.write('d');
await tick();
ok('d in modal', /Files \(\d+\//.test(f()));
stdin.write('n');
await tick();
ok('main keys ignored in modal', f().includes('Files ('));
stdin.write('q');
await tick();
ok('q closes modal', f().includes('[1/'));
stdin.write('f');
await tick();
stdin.write('j');
await tick();
stdin.write('\r');
await tick();
ok('enter jumps', f().includes('[2/'));
stdin.write('f');
await tick();
stdin.write('\x1b');
await tick();
ok('esc closes', f().includes('[2/') && !f().includes('Files ('));
stdin.write('?');
await tick();
ok('help opens', f().includes('Help') && f().includes('d/u'));
stdin.write('f');
await tick();
ok('main keys ignored in help', !f().includes('Files ('));
stdin.write('q');
await tick();
ok('q closes help, app alive', !f().includes('Help') && f().includes('[2/'));
stdin.write('?');
await tick();
stdin.write('?');
await tick();
ok('? closes help', !f().includes('Help'));
stdin.write('?');
await tick();
stdin.write('\x1b');
await tick();
ok('esc closes help', !f().includes('Help'));
console.log('unified header', f().includes('[unified]'));
stdin.write('s');
await tick();
ok('s -> split', f().includes('[split]') && f().includes('│'));
const splitFrame = f();
stdin.write('?');
await tick();
const helpFrame = f();
stdin.write('?');
await tick();
stdin.write('s');
await tick();
ok('s -> unified', f().includes('[unified]') && !f().includes('│'));
const nar = render(<App args={[]} cwd={cwd} split />);
Object.defineProperty(nar.stdout, 'columns', {value: 80});
await tick();
nar.stdin.write('s');
nar.stdin.write('s');
await tick();
ok('narrow fallback', (nar.lastFrame() ?? '').includes('too narrow for split'));
{
	const r = render(<App args={[]} cwd={cwd} />);
	await tick();
	r.stdin.write('n');
	await tick();
	const g = () => r.lastFrame() ?? '';
	ok('full: big.ts', g().includes('big.ts') && g().includes('[full]'));
	const first = () => Number(/\((\d+)-/.exec(g())?.[1]);
	ok('initial scroll on first change', g().includes('v30 = 2') && first() > 1 && g().includes('v27 = 1'));
	r.stdin.write('g');
	await tick();
	ok('g top, far line shown', g().includes('v1 = 1') && !g().includes('v30 = 2'));
	const total = Number(/\/(\d+)\)/.exec(g())?.[1]);
	r.stdin.write(']');
	await tick();
	ok('] next change', g().includes('v30 = 2'));
	r.stdin.write('[');
	await tick();
	ok('[ no earlier change, stays', first() === 28 && g().includes('v30 = 2'));
	r.stdin.write('c');
	await tick();
	const t2 = Number(/\/(\d+)\)/.exec(g())?.[1]);
	ok(
		'c -> changes-only, fewer rows',
		g().includes('[changes]') && g().includes('big.ts') && t2 < total && !g().includes('v1 = 1'),
	);
	r.stdin.write('c');
	await tick();
	ok('c -> full again, same file', g().includes('[full]') && g().includes('big.ts') && g().includes('v27 = 1'));
	console.log(g());
}
{
	const d = render(<App args={[]} cwd={cwd} />);
	await tick();
	ok('theme default solarized', (d.lastFrame() ?? '').includes('[solarized]'));
	const r = render(<App args={[]} cwd={cwd} theme="vibrant" />);
	await tick();
	const g = () => r.lastFrame() ?? '';
	ok('theme prop vibrant', g().includes('[vibrant]'));
	for (const n of ['dull', 'contrast', 'colorblind', 'light', 'solarized', 'vibrant']) {
		r.stdin.write('t');
		await tick();
		ok('t -> ' + n, g().includes(`[${n}]`));
	}
	r.stdin.write('f');
	await tick();
	r.stdin.write('t');
	await tick();
	ok('t ignored in file modal', g().includes('Files (') && g().includes('[vibrant]'));
	r.stdin.write('q');
	await tick();
	r.stdin.write('?');
	await tick();
	ok('help lists t', /\bt\s+cycle theme/.test(g()));
	r.stdin.write('t');
	await tick();
	ok('t ignored in help', g().includes('[vibrant]'));
	r.stdin.write('q');
	await tick();
	const h0 = g();
	r.stdin.write('T');
	await tick();
	ok('T does nothing in main view', !g().includes('Themes') && g() === h0);
	const c = render(<App args={[]} cwd={cwd} theme="dull" />);
	await tick();
	ok('theme prop initial', (c.lastFrame() ?? '').includes('[dull]'));
	for (const n of ['light', 'colorblind', 'solarized']) {
		const x = render(<App args={[]} cwd={cwd} theme={n as ThemeName} />);
		await tick();
		ok('theme prop ' + n, (x.lastFrame() ?? '').includes(`[${n}]`));
	}
}
{
	const dir = join(process.env.CLAUDE_JOB_DIR ?? '/tmp', 'tmp', 'keys-cfg');
	mkdirSync(dir, {recursive: true});
	const cp = join(dir, `c${Date.now()}.json`);
	const r = render(<App args={[]} cwd={cwd} theme="vibrant" configPath={cp} />);
	await tick();
	r.stdin.write('t');
	await tick();
	ok('t does not write config', !existsSync(cp));
}
{
	const dir = join(process.env.CLAUDE_JOB_DIR ?? '/tmp', 'tmp', 'keys-cfg');
	mkdirSync(dir, {recursive: true});
	const cp = join(dir, `cm${Date.now()}.json`);
	const r = render(<App args={[]} cwd={cwd} theme="vibrant" configPath={cp} />);
	await tick();
	const g = () => r.lastFrame() ?? '';
	const cfg = () => JSON.parse(readFileSync(cp, 'utf8'));
	r.stdin.write('C');
	await tick();
	ok(
		'C opens config, lists 4',
		g().includes('Config') && /theme/.test(g()) && /mode/.test(g()) && /split/.test(g()) && /view\s+\[full\]/.test(g()),
	);
	r.stdin.write('n');
	await tick();
	r.stdin.write('s');
	await tick();
	ok('other keys ignored in config', g().includes('Config') && g().includes('[unified]'));
	r.stdin.write('l');
	await tick();
	ok('l previews theme, not saved', g().includes('Config') && g().includes('[dull]') && !existsSync(cp));
	r.stdin.write('\x1b');
	await tick();
	ok('esc reverts theme preview', !g().includes('Config') && g().includes('[vibrant]') && !existsSync(cp));
	r.stdin.write('C');
	await tick();
	r.stdin.write('l');
	await tick();
	r.stdin.write('\r');
	await tick();
	ok('enter selects + saves theme', g().includes('[dull]') && cfg().theme === 'dull');
	r.stdin.write('j');
	await tick();
	r.stdin.write('l');
	await tick();
	ok('l on mode only moves cursor', !cfg().view?.mode && !g().includes('[staged]'));
	r.stdin.write('\r');
	await tick();
	ok('enter selects mode', g().includes('[staged]') && cfg().view.mode === 'staged');
	r.stdin.write('h');
	await tick();
	r.stdin.write('\r');
	await tick();
	ok('h + enter mode back', g().includes('[all]') && cfg().view.mode === 'all');
	r.stdin.write('j');
	await tick();
	r.stdin.write('l');
	await tick();
	r.stdin.write('\r');
	await tick();
	ok('split on', g().includes('[split]') && cfg().view.split === true);
	r.stdin.write('j');
	await tick();
	r.stdin.write('\r');
	await tick();
	ok('enter on current does not cycle', g().includes('[full]') && cfg().view?.full !== false);
	r.stdin.write('l');
	await tick();
	r.stdin.write('\r');
	await tick();
	ok('full off', g().includes('[changes]') && cfg().view.full === false && cfg().theme === 'dull');
	r.stdin.write('\x1b');
	await tick();
	ok('esc closes config', !g().includes('Config'));
	r.stdin.write('c');
	await tick();
	ok('c still toggles', g().includes('[full]'));
	r.stdin.write('C');
	await tick();
	r.stdin.write('C');
	await tick();
	ok('C closes config', !g().includes('Config'));
	r.stdin.write('?');
	await tick();
	ok('help lists C', /\bC\s+config/.test(g()));
}
{
	const b = render(<App args={[]} cwd={cwd} />);
	const bf = () => b.lastFrame() ?? '';
	await tick();
	b.stdin.write('F');
	await tick();
	ok('F opens search', bf().includes('Search ('));
	b.stdin.write('j');
	b.stdin.write('q');
	await tick();
	ok('j/q are text', bf().includes('> jq') && bf().includes('Search ('));
	b.stdin.write('\x7f');
	b.stdin.write('\x7f');
	b.stdin.write('big');
	await tick();
	ok('backspace + fuzzy', bf().includes('> big') && bf().includes('Search (1/1)'));
	b.stdin.write('\x1b');
	await tick();
	ok('esc closes search', !bf().includes('Search (') && bf().includes('[1/'));
	b.stdin.write('F');
	await tick();
	ok('empty query lists all', bf().includes('README.md') && bf().includes('x.bin'));
	b.stdin.write('\x0e');
	await tick();
	ok('ctrl-n moves', bf().includes('Search (2/'));
	b.stdin.write('\x10');
	await tick();
	ok('ctrl-p moves', bf().includes('Search (1/'));
	b.stdin.write('a.ts');
	await tick();
	b.stdin.write('\r');
	await tick();
	await tick();
	ok('enter -> browse', bf().includes('[browse]') && bf().includes('src/a.ts') && !bf().includes('Search ('));
	ok('browse no diff header', !bf().includes('[all]') && !bf().includes('[1/'));
	ok('browse one gutter', !/^\s*1\s+1\s/m.test(bf()) && /^\s*1\s/m.test(bf()));
	b.stdin.write('n');
	await tick();
	ok('n ignored in browse', bf().includes('src/a.ts'));
	b.stdin.write('j');
	b.stdin.write('G');
	b.stdin.write('g');
	await tick();
	ok('scroll keys ok', bf().includes('[browse]'));
	b.stdin.write('t');
	await tick();
	ok('theme key in browse', bf().includes('[browse]'));
	b.stdin.write('F');
	await tick();
	ok('F in browse opens search', bf().includes('Search ('));
	b.stdin.write('\x1b');
	await tick();
	b.stdin.write('\x1b');
	await tick();
	ok('esc leaves browse', bf().includes('[1/') && !bf().includes('[browse]'));
	b.stdin.write('?');
	await tick();
	ok('help lists F', /\bF\s+search/.test(bf()));
	b.unmount();
}
{
	const {execSync} = await import('node:child_process');
	const {mkdtempSync, writeFileSync} = await import('node:fs');
	const dir = mkdtempSync(join(process.env.CLAUDE_JOB_DIR ?? '.', 'tmp', 'nochg-'));
	const sh = (c: string) => execSync(c, {cwd: dir, stdio: 'ignore'});
	sh('git init -q');
	writeFileSync(join(dir, 'hello.txt'), 'hello world\n');
	writeFileSync(join(dir, 'bin.dat'), Buffer.from([65, 0, 66]));
	sh('git add -A');
	sh('git -c user.email=a@b -c user.name=n commit -qm init');
	const n = render(<App args={[]} cwd={dir} />);
	const nf = () => n.lastFrame() ?? '';
	await new Promise((r) => setTimeout(r, 400));
	ok('no changes shown', nf().includes('No changes'));
	n.stdin.write('F');
	await tick();
	ok('no-changes F opens search', nf().includes('Search ('));
	n.stdin.write('hello');
	await tick();
	n.stdin.write('\r');
	await tick();
	ok('no-changes browse shows content', nf().includes('[browse]') && nf().includes('hello world'));
	n.stdin.write('\x1b');
	await tick();
	n.stdin.write('?');
	await tick();
	ok('no-changes help opens', nf().includes('Help'));
	n.stdin.write('?');
	await tick();
	n.stdin.write('F');
	await tick();
	n.stdin.write('bin');
	await tick();
	n.stdin.write('\r');
	await tick();
	ok('binary file not shown', nf().includes('binary file, not shown'));
	n.unmount();
}
console.log(splitFrame);
console.log(helpFrame);
process.exit(fail ? 1 : 0);
